# Generated by Django 5.2 on 2025-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма пополнения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Снятие')], max_length=10, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма снятия'),
        ),
    ]
